name: build-dotnet

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '3.1.402' # The .NET SDK version to use

jobs:
  build:

    name: build-ubunto
    runs-on: ubuntu-latest
  
    steps:
    - name: 'Init - Checkout'
      uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      shell: bash
      working-directory: ./
    
    - name: List Dependencies
      run: dotnet list package > dependencies.txt
      shell: bash
      
    - name: Collect Dependencies
      uses: actions/upload-artifact@v2
      with:
        name: Dependencies
        path: dependencies.txt
        
    - name: List Dependency Updates
      run: dotnet list package --outdated > dependencyUpdates.txt
      shell: bash
      
    - name: Collect Dependency Updates
      uses: actions/upload-artifact@v2
      with:
        name: Dependencies Updates
        path: dependencyUpdates.txt
      
    - name: Test
      run: dotnet test -l:trx || true
      shell: bash
    - if: always()
      name: Report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsDotNetDownloadableArtifact
        path: ./PracticoUT2/bin/release/net5.0/*.*
