name: build-dotnet

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  build:

    name: build-win
    runs-on: windows-latest
  
    steps:
    - name: 'Init - Checkout'
      uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: 'Fin build'
      run: |
        echo 'Finalizó el build'
        
    - name: Run tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsDotNetDownloadableArtifact
        path: ./PracticoUT2/bin/release/net5.0/*.*
