name: build-dotnet

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.sln'
      - '**.csproj'

env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  build:

    name: build-win
    runs-on: windows-latest
  
    steps:
    - name: 'Init - Checkout'
      uses: actions/checkout@v2
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./
      
    - name: Build
      run: dotnet build PracticoUT2.sln --configuration Release --no-restore
        
    - name: Test
      run: dotnet test UnitTestPracticoUT2v2/UnitTestPracticoUT2v2.csproj -l:trx || true
      shell: bash
    - if: always()
      name: Report
      uses: dorny/test-reporter@v1
      with:
        name: DotNET Tests
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: 'false'
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsDotNetDownloadableArtifact
        path: ./PracticoUT2/bin/release/net5.0/*.*
        
    - name: Upload tests results
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GitHubActionsTestsResults
        path: '**/*.trx'
